3. Data Sources

3.1 Main dataset: Demandes de Valeurs Foncières (DVF)

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import os

os.listdir("/content/drive/MyDrive/Projet_IA")

['77288_000AE.csv']

In [8]:
import pandas as pd

# Parcelle "AE"
df = pd.read_csv("/content/drive/MyDrive/Projet_IA/77288_000AE.csv", sep = ";")
df.head()

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
0,2025-381473,2025-06-18,1,Vente,124500.0,68.0,NaN,AV DU GENERAL PATTON,850,77000,...,38.0,2.0,NaN,NaN,NaN,NaN,NaN,2.648564,48.548987,000AE
1,2025-381473,2025-06-18,1,Vente,124500.0,68.0,NaN,AV DU GENERAL PATTON,850,77000,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2.648564,48.548987,000AE
2,2025-381002,2025-05-21,1,Vente,94000.0,7.0,NaN,AV DU GENERAL PATTON,850,77000,...,63.0,3.0,NaN,NaN,NaN,NaN,NaN,2.650122,48.545957,000AE
3,2025-381020,2025-05-21,1,Vente,145000.0,7.0,NaN,AV DU GENERAL PATTON,850,77000,...,77.0,2.0,NaN,NaN,NaN,NaN,NaN,2.650122,48.545957,000AE
4,2025-381002,2025-05-21,1,Vente,94000.0,7.0,NaN,AV DU GENERAL PATTON,850,77000,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2.650122,48.545957,000AE

In [11]:
df.describe()

,numero_disposition,valeur_fonciere,adresse_numero,adresse_code_voie,code_postal,code_commune,code_departement,ancien_code_commune,ancien_nom_commune,ancien_id_parcelle,...,lot4_surface_carrez,lot5_numero,lot5_surface_carrez,nombre_lots,code_type_local,surface_reelle_bati,nombre_pieces_principales,surface_terrain,longitude,latitude
count,753.000000,7.530000e+02,687.000000,753.000000,753.0,753.0,753.0,0.0,0.0,0.0,...,1.0,1.0,0.0,753.000000,574.000000,287.000000,574.000000,143.000000,753.000000,753.000000
mean,1.045153,2.688119e+05,72.393013,519.628154,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,0.922975,2.505226,107.839721,1.294425,509.433566,2.648867,48.547540
std,0.207777,7.614106e+05,484.087148,386.728429,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.633225,0.698395,419.090493,2.013585,1052.515334,0.002352,0.002063
min,1.000000,1.000000e+00,1.000000,45.000000,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,0.000000,1.000000,13.000000,0.000000,1.000000,2.642018,48.545652
25%,1.000000,1.200000e+05,10.000000,90.000000,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,1.000000,2.000000,42.000000,0.000000,16.500000,2.647871,48.545652
50%,1.000000,1.640000e+05,44.000000,510.000000,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,1.000000,3.000000,60.000000,0.000000,113.000000,2.649742,48.546536
75%,1.000000,2.120000e+05,89.000000,850.000000,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,1.000000,3.000000,73.000000,2.000000,357.500000,2.650580,48.549543
max,2.000000,8.689292e+06,9002.000000,1690.000000,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,9.000000,4.000000,6471.000000,23.000000,5564.000000,2.651481,48.552266

In [10]:
df_clean = df.dropna(how="all")
df_clean.describe()

,numero_disposition,valeur_fonciere,adresse_numero,adresse_code_voie,code_postal,code_commune,code_departement,ancien_code_commune,ancien_nom_commune,ancien_id_parcelle,...,lot4_surface_carrez,lot5_numero,lot5_surface_carrez,nombre_lots,code_type_local,surface_reelle_bati,nombre_pieces_principales,surface_terrain,longitude,latitude
count,753.000000,7.530000e+02,687.000000,753.000000,753.0,753.0,753.0,0.0,0.0,0.0,...,1.0,1.0,0.0,753.000000,574.000000,287.000000,574.000000,143.000000,753.000000,753.000000
mean,1.045153,2.688119e+05,72.393013,519.628154,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,0.922975,2.505226,107.839721,1.294425,509.433566,2.648867,48.547540
std,0.207777,7.614106e+05,484.087148,386.728429,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.633225,0.698395,419.090493,2.013585,1052.515334,0.002352,0.002063
min,1.000000,1.000000e+00,1.000000,45.000000,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,0.000000,1.000000,13.000000,0.000000,1.000000,2.642018,48.545652
25%,1.000000,1.200000e+05,10.000000,90.000000,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,1.000000,2.000000,42.000000,0.000000,16.500000,2.647871,48.545652
50%,1.000000,1.640000e+05,44.000000,510.000000,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,1.000000,3.000000,60.000000,0.000000,113.000000,2.649742,48.546536
75%,1.000000,2.120000e+05,89.000000,850.000000,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,1.000000,3.000000,73.000000,2.000000,357.500000,2.650580,48.549543
max,2.000000,8.689292e+06,9002.000000,1690.000000,77000.0,77288.0,77.0,NaN,NaN,NaN,...,59.5,26.0,NaN,9.000000,4.000000,6471.000000,23.000000,5564.000000,2.651481,48.552266

In [12]:
df.columns

Index(['id_mutation', 'date_mutation', 'numero_disposition', 'nature_mutation',
       'valeur_fonciere', 'adresse_numero', 'adresse_suffixe',
       'adresse_nom_voie', 'adresse_code_voie', 'code_postal', 'code_commune',
       'nom_commune', 'code_departement', 'ancien_code_commune',
       'ancien_nom_commune', 'id_parcelle', 'ancien_id_parcelle',
       'numero_volume', 'lot1_numero', 'lot1_surface_carrez', 'lot2_numero',
       'lot2_surface_carrez', 'lot3_numero', 'lot3_surface_carrez',
       'lot4_numero', 'lot4_surface_carrez', 'lot5_numero',
       'lot5_surface_carrez', 'nombre_lots', 'code_type_local', 'type_local',
       'surface_reelle_bati', 'nombre_pieces_principales',
       'code_nature_culture', 'nature_culture', 'code_nature_culture_speciale',
       'nature_culture_speciale', 'surface_terrain', 'longitude', 'latitude',
       'section_prefixe'],
      dtype='object')

In [14]:
df_clean["nature_mutation"].value_counts()

nature_mutation
Vente                                 505
Vente en l'état futur d'achèvement    245
Adjudication                            3
Name: count, dtype: int64

In [18]:
df_clean= df_clean[df["nature_mutation"] == "Vente"]
df_clean["nature_mutation"].value_counts()

/tmp/ipykernel_186/3542312386.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_clean= df_clean[df["nature_mutation"] == "Vente"]

nature_mutation
Vente    505
Name: count, dtype: int64

In [22]:
df_clean = df_clean[df_clean["type_local"].isin(["Maison", "Appartement"])]

df_clean["type_local"].value_counts()

type_local
Appartement    150
Maison          43
Name: count, dtype: int64

In [23]:
carrez_cols = [
    "lot1_surface_carrez",
    "lot2_surface_carrez",
    "lot3_surface_carrez",
    "lot4_surface_carrez",
    "lot5_surface_carrez"
]

df_clean["surface_carrez_totale"] = df_clean[carrez_cols].sum(axis=1, skipna=True)

In [24]:
lot_cols = [
    "lot1_numero",
    "lot2_numero",
    "lot3_numero",
    "lot4_numero",
    "lot5_numero"
]

df_clean["nb_lots_renseignes"] = df_clean[lot_cols].notna().sum(axis=1)

In [25]:
df_clean[["surface_carrez_totale", "nb_lots_renseignes"]].head()

   surface_carrez_totale  nb_lots_renseignes
0                   0.00                   1
2                   0.00                   2
3                  78.73                   1
6                  62.26                   2
9                 158.00                   2

In [26]:
df_clean = df_clean.drop(columns=carrez_cols + lot_cols)